<<<<<<< Updated upstream
# H2 Console ?? (?? ???? DB ??? ??? ???? ??
=======
# H2 Console ?? (?? ???? DB ??? ??? ???? ??)
>>>>>>> Stashed changes
# H2 ?? ?? URL: http://localhost:8080/h2-console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

<<<<<<< Updated upstream
# ??? ?? ??
=======
# ??? ?? ?? (DB ?? ??)
>>>>>>> Stashed changes
spring.datasource.url=jdbc:h2:mem:mealdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA/Hibernate ??
<<<<<<< Updated upstream
# ddl-auto: create-drop? ??? ???? ??? ???? ?? ???? ???? ??????.
# ?? ??? ?? ??? ?? ? ????, ???? 'update'? ???? ???.
spring.jpa.hibernate.ddl-auto=create-drop
# SQL ??? ??? ???? ???? ????.
spring.jpa.show-sql=true
# ???? SQL? ??? ?????.
spring.jpa.properties.hibernate.format_sql=true


=======
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
>>>>>>> Stashed changes
